ALTER TABLE units DROP COLUMN current_rent;

ALTER TABLE leases ADD COLUMN rent NUMERIC(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE leases ADD COLUMN deposit NUMERIC(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE leases ADD COLUMN deposit_paid_date TIMESTAMP;
ALTER TABLE leases ADD COLUMN deposit_returned NUMERIC(10,2);
ALTER TABLE leases ADD COLUMN deposit_return_date TIMESTAMP;
